### ISSUE TITLE
Enhancement: Slurm support

### ISSUE THREAD

**Issue by edublancas** [ploomber/soopervisor#18]
We got a request to add support for Slurm. I asked a few people and this sounds like a great opportunity for Ploomber to help researchers since many university clusters use Slurm. So, we'll do it. You can see the original discussion (with sample code) [here](https://github.com/ploomber/ploomber/issues/428). Essentially, we want to add Slurm as another supported backend to soopervisor.

I still need to draft a more detailed description, I'll grab the pieces from the original issue and post them here. We're aiming for 2-3 weeks to do an initial release with basic support.

**Comment by ajasja** [comment]
This is great.
I've recently switched labs and our new cluster uses [SGE](https://qpeng.org/prog/sge.htm). The logic is very similar to SLURM, so I think the exact same soopervisor logic, just different subprocess commands would work. I'm not opening a separate issue yet, because it makes sense to get SLURM working first, but maybe there are some design decisions that would make extending easier.

**Comment by edublancas** [comment]
Great, thanks a lot for your feedback! I'll post progress here.

**Comment by edublancas** [comment]
Hi thanks for your patience, I've created a new branch to work on the Slurm (and SGE by extension) integration: https://github.com/ploomber/soopervisor/tree/slurm will ping you once I have the first iteration for you to test it

**Comment by edublancas** [comment]
An initial version of the SLURM integration is available in the master branch.

[Click here to go to the tutorial.](https://soopervisor.readthedocs.io/en/latest/tutorials/slurm.html)

Features:
1. Submit pipelines
2. Jobs abort if any dependency fails
3. Only submits outdated tasks (source code has changed) but can  force the execution of all tasks

There are a few minor things I need to work on (#19, #20).

Please comment on any feedback you may have.

**Comment by ajasja** [comment]
Great, thanks! I'll test it soon.

Is it possible to use different submit templates for different tasks? A concrete example is if you would like some task to run on the CPU and some on the GPU. Or some tasks with more RAM and some with less. 

My suggestions:
There could be a default `cluster/__template.sh` for all tasks and then specific `cluster/{{name}}.sh` that would override that. 

Or there could be a cluster specific config file mapping task names to templates. This seems like more work, but could be more flexible, since several tasks could point to the same template file. In the above approach one would just make multiple copies. 

Or the template selection could go into pipeline.yaml (I'm not sure that's the best, since the pipeline should be independent of where you run it).

**Comment by edublancas** [comment]
Thanks for the feedback! I think we can combine options 1 and 2: have some naming convention to prevent adding more configuration. I imagine something like this: given a task named `fit-gpu`, use the following rules (in order):

1. Look for an exact match (`fit-gpu.sh`)
2. If no matches, look for a glob-like file (e.g., `fit-*.sh`, or `*-gpu.sh`)
3. If no matches, use the default `template.sh`

What do you think?

**Comment by ajasja** [comment]
Sounds like a good idea! Do you think there is a possibility that the wrong template gets picked with the globs? Not sure what should be the default split char (`-`, `_` or even `__`). I would go with `__` so that you can still name the tasks `with-the-other-options__gpu`. Also I would name the default template `__template.sh`, so that you can have a task named template with a non-default template:)

**Comment by edublancas** [comment]
Thanks for the feedback! I implemented the templating feature (using double underscore). I kept `template.sh` because I felt like `_template.sh` would be confusing for users since we're using underscores for the name matching feature.

[I updated the tutorial](https://soopervisor.readthedocs.io/en/latest/tutorials/slurm.html)

Let me know if you have any other feedback. Otherwise, I'll make a stable release. 🎉

**Comment by edublancas** [comment]
This will be part of the next release `0.6`, coming up in the next few days. Feel free to open a new issue if there is any feedback.

**Comment by ajasja** [comment]
Looks good to me so far (although grant dedlines are coming up so I did not test it with real real world problems:)
Thanks for implementing this!

**Comment by edublancas** [comment]
No rush! Feel free to share your feedback whenever you have time!

Do you know anyone who may want to try this out? Happy to reach out to them (ping me on Slack if that's the case)
